apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pop
  name: pop
spec:
  containers:
  - image: nginx
    name: pop
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
