apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "0.5" # limite máximo vai ser 50% de 1 CPU
        memory: "128Mi"
      requests:
        cpu: "0.3" # vai garantir pelo menos 30% de 1 CPU
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
